### ISSUE TITLE
Install not working with Python 3.8.5

### ISSUE THREAD

**Issue by ScrapeFlare** [scrapy/scrapely#121]
Last few lines of error:

`   scrapely/_htmlpage.c:333:75: note: in definition of macro ‘__Pyx_PyCode_New’
      333 |           PyCode_New(a, 0, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
          |                                                                           ^~~~~
    In file included from /usr/include/python3.8/compile.h:5,
                     from /usr/include/python3.8/Python.h:138,
                     from scrapely/_htmlpage.c:19:
    /usr/include/python3.8/code.h:122:28: note: expected ‘PyObject *’ {aka ‘struct _object *’} but argument is of type ‘int’
      122 | PyAPI_FUNC(PyCodeObject *) PyCode_New(
          |                            ^~~~~~~~~~
    scrapely/_htmlpage.c:333:11: error: too many arguments to function ‘PyCode_New’
      333 |           PyCode_New(a, 0, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
          |           ^~~~~~~~~~
    scrapely/_htmlpage.c:11442:15: note: in expansion of macro ‘__Pyx_PyCode_New’
    11442 |     py_code = __Pyx_PyCode_New(
          |               ^~~~~~~~~~~~~~~~
    In file included from /usr/include/python3.8/compile.h:5,
                     from /usr/include/python3.8/Python.h:138,
                     from scrapely/_htmlpage.c:19:
    /usr/include/python3.8/code.h:122:28: note: declared here
      122 | PyAPI_FUNC(PyCodeObject *) PyCode_New(
          |                            ^~~~~~~~~~
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-iy634a0o/scrapely/setup.py'"'"'; __file__='"'"'/tmp/pip-install-iy634a0o/scrapely/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-o5t_b1tg/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/pijus/.local/include/python3.8/scrapely Check the logs for full command output.
`

**Comment by vad** [comment]
I've pushed a new package supporting python 3.10+ on https://pypi.org/project/sd-scrapely/
